### PR TITLE
Add Kinova Gen3 7dof

### PR DESCRIPTION
**Pull request by dyackzan**
Please let me know if there are any improvements to the model you all would suggest. One issue we noticed is some weird collision behavior as demonstrated in this comment: https://github.com/PickNikRobotics/mujoco_menagerie/pull/1#pullrequestreview-2100313823.

### CODE REVIEW

**Comment by dyackzan** [comment]
Reading through section 7 of the CLA:

> Should You wish to submit work that is not Your original creation, You may submit it to Google separately from any Contribution, identifying the complete details of its source and of any license or other restriction (including, but not limited to, related patents, trademarks, and license agreements) of which you are personally aware, and conspicuously marking the work as "Submitted on behalf of a third-party: [named here]".

The Kinova mesh files in this PR are from the https://github.com/Kinovarobotics/ros2_kortex/tree/main/kortex_description/arms/gen3/7dof/meshes repo. Which is from Kinova inc. under the license I included in this PR. Based on those files should I change the name of this PR to "Submitted on behalf of a third-party: Kinova inc."?

**Comment by kevinzakka** [comment]
Hi @dyackzan and @adlarkin, first off, really appreciate this PR. Thank you for contributing to this open-source project!

We actually have an MJCF of the Kinova which we were going to submit to Menagerie sometime soon. There's a few compelling reasons for using it as opposed to this one:

1. It uses 7 STL files as opposed to 26 OBJ files so it has a smaller memory footprint. OBJ files seem overkill for the Kinova since the arm is basically white?
2. It looks like some of your links are rotated the wrong way (compare to MJCF below)?

image

Given the above, would it be okay if we get the other MJCF merged in as opposed to this one?

**Comment by adlarkin** [comment]
Hey @kevinzakka, based on the reasons you provided, I think it makes sense to close this PR in favor of the Kinova MJCF you're planning on adding soon. Thanks for the update!

**Comment by dyackzan** [comment]
I agree, thank you for updating us on this so quickly. Closing this PR in favor of your future PR

**Pull request closed without merging**
