### PR TITLE
WIP: feat: add Atlas description

### PR DESCRIPTION
**Pull request by lvjonok**
This PR adds an Atlas description. I attempted to follow contribution guidelines, in `README.md` you can find notes on the process of converting URDF to MuJoCo.

What help I am needed:
- licence: I have used URDF from [drake](https://github.com/RobotLocomotion/drake/tree/master) project. So, probably the licence should be copied from there, but I am unaware.
- textures: I have found another [URDF description](https://github.com/team-vigir/vigir_atlas_common/tree/master/atlas_description) of Atlas which also contained textures and .dae files. My attempt was to use [drake textures](https://github.com/RobotLocomotion/drake/tree/73a8da32cd41ff7fd023c3680f8250860cbd0e6b/examples/atlas/urdf/materials/textures) and add them to `.xml` using mapping (which .obj should use which textures) from `.dae` files. I have added an example of textures loading to `utorso` mesh because it will be more convenient to try for others.

### CODE REVIEW

**Comment by kevinzakka** [comment]
Regarding the license, it looks like it's a 3-clause BSD license so we can accept it. You can just copy paste that license verbatim.

**Comment by lvjonok** [comment]
Hello! When I could expect any further feedback or suggestions regarding textures mapping?

**Comment by yuvaltassa** [comment]
Hi, can you please clarify the issue with the textures? 
I find the item in the OP regarding this issue quite unclear.

**Comment by lvjonok** [comment]
> Hi, can you please clarify the issue with the textures? I find the item in the OP regarding this issue quite unclear.

In the original repository there are .DAE files with textures. I took as example `utorso` body and tried to apply textures I have found in `.dae` file.

1. The first question I have is can I add two textures to one body? In the corresponding `.dae` file I see that it loads two `.jpg` files.
2. The next question is how to actually understand parameters for the material component based on `.dae` file. Do I have to add some external parameters based on original mesh file?

That is why I have added the scene `textures.xml` which one can load and check that textures are loaded correctly.

**Comment by kevinzakka** [comment]
Hi @lvjonok, the licensing is impossible to trace for this model and it looks like the Drake URL you linked is no longer valid. I'm going to go ahead and close this PR for now since the licensing / tracing of Atlas is a little foggy.

**Pull request closed without merging**
