### PR TITLE
Add LEAP hand.

### LINKED ISSUE #84: LEAP HAND SUPPORT
Hi,

Do you have any plans to officially support Leap Hand XML?

**URL for the existing model source (e.g. URDF)**
https://leaphand.com/

### PR DESCRIPTION
**Pull request by kevinzakka**
Fixes #84.

leap_hand

### CODE REVIEW

**Comment by kevinzakka** [comment]
cc @Lucky7Chess

**Comment by Lucky7Chess** [comment]
Yes, the right hand looks good to me @kevinzakka  I just loaded it.  Maybe we should also add the left hand also from https://leaphand.com/static/cad/urdf/leap_left.zip ?

**Comment by kevinzakka** [comment]
Awesome, thanks so much for fast review @Lucky7Chess! Agree having the left hand would be good. Is it as simple as reflecting the meshes about the z axis? I'm trying to see if we can write a script to generate the left from right to minimize bugs.

**Comment by kevinzakka** [comment]
I noticed the following differences between the left and right models:

* The left hand references a `thumb_left_temp_base` whereas this does not exist in the right hand.
* No `pip_4` in the left hand.
* Different ordering of joint names in the thumb, e.g. right order is [12, 13, 14, 15] whereas left order is [13, 12, 14, 15].
* It would seem that the meshes don't have the same origin? See the difference when the two hands are placed the world origin (pic below).

Just want to make sure that these are intentional and wanted to walk through them with you @Lucky7Chess.

left
right

**Comment by Lucky7Chess** [comment]
Sorry for some reason Github didn't notify me of your message.

Yes I wish there was an easy way to mirror but there is not it seems.  But I think the model isn't an exact mirror in this case.

None of these three things you mention are intentional actually.  The first two is just some CAD software naming I didn't change.  And the last is just how my CAD software exports and I never fixed it to a set position.  Its just a byproduct of the software I am using to get the URDF. Its a messy mix of Inventor/Onshape.  

I guess I don't use the left hand much so I haven't noticed the differences. Its probably better to fix these bugs in the left on Menagerie since that'll be what people use on MuJoCo.

**Comment by kevinzakka** [comment]
@Lucky7Chess What does `thumb_left_temp_base` correspond to? I tried replacing it with `pip` and adjusting the transform but struggling to match the right hand.

**Comment by kevinzakka** [comment]
@Lucky7Chess One last thing: I want to add an attachment site to each hand so that users can use it to attach the hand to an arm. Do you have a pos/quat that I can use for this for each hand, potentially from CAD? I couldn't find anything from parsing the original URDF.

**Comment by Lucky7Chess** [comment]
Hmm I actually never thought about adding that info to the URDF/MJCF but that's a really good idea.  I can't figure out how to get the coordinates from the URDF in the format you may want but I can get it in my CAD.   The center of the mounting holes is where the center of the arm end effector mounting point would contact the hand.   As in the photo below that is 37.5mm from the top of the top plate and 59mm from the flat side of the top plate.  

image

The top plate is the same for the right hand (the plate you are looking at on the image attached) and the left hand except it is mirrored.  So for the left hand it is 37.5 mm from the top and 59mm from the right side which is still the flat side of the top palm.

If this doesn't make sense I can also try to figure this out in URDF somehow?  I am unfamiliar with the easiest way to do that. Thank you for your help, you are an expert in this!  :)

**Comment by Lucky7Chess** [comment]
It also looks like I didn't put the mounting holes into the URDF, not sure why.  The hand typically mounts to UR5/Xarm/Franka that's why its mounted to the top of the hand to avoid the arm colliding with the table due to the kinematic structure of these arms being designed for grippers that are also top down.

**Comment by kevinzakka** [comment]
@Lucky7Chess Maybe we can have the mounting plate as part of the URDF?

**Comment by Lucky7Chess** [comment]
The plate is arm specific depending on the hole pattern of the arm...so the plate you have is just a generic one without any holes.  I guess now that I think of it the mounting position could also change slightly depending on the arm you have.  

You could leave the mounting point off I guess or just pick a center location on the top of the palm, either way is fine.

**Comment by kevinzakka** [comment]
I think I’ll go with the latter option!

The only thing is that the estimates for left and right are different because the palm meshes seem to have a different coordinate frame. I want to figure out how to make them symmetric 🥲

**Comment by Lucky7Chess** [comment]
I think its okay because as the end user its not really noticable how the meshes are setup.

**Comment by kevinzakka** [comment]
Thanks @Lucky7Chess, decided not to add an attachment site for now. We can add it in a future PR once we also validate with actual hardware!

**Comment by kevinzakka** [comment]
This is now ready for import!

**Comment by kevinzakka** [comment]
@yuvaltassa Ready for import now!

**Comment by Lucky7Chess** [comment]
Thank you so much @kevinzakka !!!

**Comment by kevinzakka** [comment]
I didn't do much, thank you for your awesome open-source contributions :)

**Review by yuvaltassa — APPROVED** [review]

**Pull request merged**
